package gui.dialogs;
import classes.consultas;
import classes.medico;
import classes.paciente;
import com.fasterxml.jackson.core.JsonProcessingException;
import gerenciador.gerenciadorDeConsultas;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class DlgCadConsulta extends javax.swing.JDialog {

    private consultas Consulta;
    private gerenciadorDeConsultas gerente;
    private paciente Paciente;
    private medico Medico;
    public DlgCadConsulta(java.awt.Frame parent, boolean modal, consultas Consulta) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovaConsulta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAddPaciente = new javax.swing.JButton();
        btnAddMedico = new javax.swing.JButton();
        btnExcluirConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtConsulta = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnFecharConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNovaConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNovaConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNovaConsulta.setText("Nova Consulta");

        btnAddPaciente.setText("Add Paciente");
        btnAddPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPacienteActionPerformed(evt);
            }
        });

        btnAddMedico.setText("Add Medico");
        btnAddMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicoActionPerformed(evt);
            }
        });

        btnExcluirConsulta.setText("Excluir Consulta");
        btnExcluirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnAddPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnAddPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAddMedico)
                    .addComponent(btnExcluirConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        edtConsulta.setColumns(20);
        edtConsulta.setRows(5);
        jScrollPane1.setViewportView(edtConsulta);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFecharConsulta.setText("Fechar Consulta");
        btnFecharConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNovaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnFecharConsulta)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNovaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnFecharConsulta))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPacienteActionPerformed
        try {
        DlgCadPaciente telaAddPaciente;
        telaAddPaciente = new DlgCadPaciente(new JFrame(),true);
        telaAddPaciente.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(DlgCadPaciente.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JsonProcessingException ex) {
        Logger.getLogger(DlgCadPaciente.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAddPacienteActionPerformed

    private void btnAddMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicoActionPerformed
         try {
        DlgCadMedico telaAddMedico;
        telaAddMedico = new DlgCadMedico(new JFrame(),true, Medico);
        telaAddMedico.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(DlgCadMedico.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JsonProcessingException ex) {
        Logger.getLogger(DlgCadMedico.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAddMedicoActionPerformed

    private void btnExcluirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirConsultaActionPerformed
       String dataEscolhida = JOptionPane.showInputDialog("informe a data da consulta que deseja excluir: ");
        consultas c = this.gerente.buscar(dataEscolhida);
        if(c == null){
            JOptionPane.showMessageDialog(this, "nao existe essa data de consulta");
        }else{
                gerente.Remover(dataEscolhida);
                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }
        edtConsulta.setText(this.Consulta.toString());
    }//GEN-LAST:event_btnExcluirConsultaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int response = JOptionPane.showConfirmDialog(null,
                    "Deseja realmente cancelar esta consulta?",
                    "Confirm",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                dispose();
            }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFecharConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharConsultaActionPerformed
        String dataEscolhida = JOptionPane.showInputDialog("informe o data da consulta que deseja excluir: ");
        consultas c = this.gerente.buscar(dataEscolhida);
        if(c == null){
            JOptionPane.showMessageDialog(this, "nao existe essa data de consulta");
        }else{
                gerente.Remover(dataEscolhida);
                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }
        edtConsulta.setText(this.Consulta.toString());
    }//GEN-LAST:event_btnFecharConsultaActionPerformed

    public void atualizarInterfaceDoPedido(){
        String texto = this.Consulta.toString();
        edtConsulta.setText(texto);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedico;
    private javax.swing.JButton btnAddPaciente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirConsulta;
    private javax.swing.JButton btnFecharConsulta;
    private javax.swing.JTextArea edtConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNovaConsulta;
    // End of variables declaration//GEN-END:variables
}
