/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;

import classes.Alunos;
import classes.Disciplina;
import classes.Professor;
import com.fasterxml.jackson.core.JsonProcessingException;
import gerenciador.GerenciadorDeDisciplinas;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class dlgCadDisciplina extends javax.swing.JDialog {
private Disciplina disciplina;
private GerenciadorDeDisciplinas gerente;
private Alunos aluno;
   
    public dlgCadDisciplina(java.awt.Frame parent, boolean modal, Disciplina disciplina) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovaDisciplina = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAddAluno = new javax.swing.JButton();
        btnAddProfessor = new javax.swing.JButton();
        btnExcluirDisciplina = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDisicplina = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnFecharDisciplina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNovaDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNovaDisciplina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNovaDisciplina.setText("Nova Disciplina");

        btnAddAluno.setText("Add Aluno");
        btnAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlunoActionPerformed(evt);
            }
        });

        btnAddProfessor.setText("Add Professor");
        btnAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProfessorActionPerformed(evt);
            }
        });

        btnExcluirDisciplina.setText("Excluir Disicplina");
        btnExcluirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAddAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        edtDisicplina.setColumns(20);
        edtDisicplina.setRows(5);
        jScrollPane1.setViewportView(edtDisicplina);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFecharDisciplina.setText("Fechar Disciplina");
        btnFecharDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNovaDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFecharDisciplina)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNovaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnFecharDisciplina)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProfessorActionPerformed
    try {
        dlgCadProfessor telaAddDisciplina;
        telaAddDisciplina = new dlgCadProfessor(new JFrame(),true);
        telaAddDisciplina.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(dlgCadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JsonProcessingException ex) {
        Logger.getLogger(dlgCadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAddProfessorActionPerformed

    private void btnFecharDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharDisciplinaActionPerformed
        if(this.disciplina == null){
        }else if(this.disciplina.getNome() == null){
            JOptionPane.showConfirmDialog(this, "Voce nao selecionou a disciplina");
        }else if(this.disciplina.getNome() != null){
            JOptionPane.showConfirmDialog(this,"Disciplina selecionada com sucesso");
        }
    }//GEN-LAST:event_btnFecharDisciplinaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       int response = JOptionPane.showConfirmDialog(null,
                    "Deseja realmente cancelar esta disciplina?",
                    "Confirm",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                dispose();
            }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlunoActionPerformed
    try {
        dlgCadAluno telaAddDisciplina;
        telaAddDisciplina = new dlgCadAluno(new JFrame(),true, aluno);
        telaAddDisciplina.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(dlgCadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JsonProcessingException ex) {
        Logger.getLogger(dlgCadDisciplina.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAddAlunoActionPerformed

    private void btnExcluirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDisciplinaActionPerformed
        String nomeEscolhido = JOptionPane.showInputDialog("informe o nome da disciplina que deseja excluir: ");
        Disciplina g = this.gerente.buscar(nomeEscolhido);
        if(g == null){
            JOptionPane.showMessageDialog(this, "nao existe esse nome de disciplina");
        }else{
                gerente.remover(nomeEscolhido);
                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }
        edtDisicplina.setText(this.disciplina.toString());
    }//GEN-LAST:event_btnExcluirDisciplinaActionPerformed

    public void atualizarInterfaceDoPedido(){
        String texto = this.disciplina.toString();
        edtDisicplina.setText(texto);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAluno;
    private javax.swing.JButton btnAddProfessor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirDisciplina;
    private javax.swing.JButton btnFecharDisciplina;
    private javax.swing.JTextArea edtDisicplina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNovaDisciplina;
    // End of variables declaration//GEN-END:variables
}
