/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;
import classes.Reservas;
import classes.Hospedes;
import classes.Quartos;
import gerenciador.GerenciadorDeReservas;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class DlgCadReservas extends javax.swing.JDialog {
private Reservas Reserva;
    private GerenciadorDeReservas gerente;
    private Quartos quarto;
    private Hospedes hospede;
    
    public DlgCadReservas(java.awt.Frame parent, boolean modal, Reservas reserva) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAddHospedes = new javax.swing.JButton();
        btnAddQuartos = new javax.swing.JButton();
        btnExcluirReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtReserva = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnFecharReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nova Reserva");

        btnAddHospedes.setText("Add Hospedes");
        btnAddHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospedesActionPerformed(evt);
            }
        });

        btnAddQuartos.setText("Add Quartos");
        btnAddQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQuartosActionPerformed(evt);
            }
        });

        btnExcluirReserva.setText("Excluir Reserva");
        btnExcluirReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAddHospedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHospedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        edtReserva.setColumns(20);
        edtReserva.setRows(5);
        jScrollPane1.setViewportView(edtReserva);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFecharReserva.setText("Fechar Reserva");
        btnFecharReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFecharReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFecharReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospedesActionPerformed
         try {
        DlgCadHospedes telaAddHospedes;
        telaAddHospedes = new DlgCadHospedes(new JFrame(),true);
        telaAddHospedes.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(DlgCadHospedes.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JsonProcessingException ex) {
        Logger.getLogger(DlgCadHospedes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAddHospedesActionPerformed

    private void btnAddQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuartosActionPerformed
           try {
        DlgCadQuartos telaAddQuartos;
        telaAddQuartos = new DlgCadQuartos(new JFrame(),true, quarto);
        telaAddQuartos.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(DlgCadQuartos.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JsonProcessingException ex) {
        Logger.getLogger(DlgCadQuartos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAddQuartosActionPerformed

    private void btnExcluirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirReservaActionPerformed
         String dataEscolhida = JOptionPane.showInputDialog("informe a data da reserva que deseja excluir: ");
        Reservas r = this.gerente.buscar(dataEscolhida);
        if(r == null){
            JOptionPane.showMessageDialog(this, "nao existe essa data de reserva");
        }else{
                gerente.remover(dataEscolhida);
                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }
        edtReserva.setText(this.Reserva.toString());
    }//GEN-LAST:event_btnExcluirReservaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         int response = JOptionPane.showConfirmDialog(null,
                    "Deseja realmente cancelar esta reserva?",
                    "Confirm",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                dispose();
            }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFecharReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharReservaActionPerformed
        String dataEscolhida = JOptionPane.showInputDialog("informe o data da REserva que deseja excluir: ");
        Reservas r = this.gerente.buscar(dataEscolhida);
        if(r == null){
            JOptionPane.showMessageDialog(this, "nao existe essa data de reserva");
        }else{
                gerente.remover(dataEscolhida);
                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }
        edtReserva.setText(this.Reserva.toString());
    }                                                 

    public void atualizarInterfaceDoPedido(){
        String texto = this.Reserva.toString();
        edtReserva.setText(texto);
    }//GEN-LAST:event_btnFecharReservaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHospedes;
    private javax.swing.JButton btnAddQuartos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirReserva;
    private javax.swing.JButton btnFecharReserva;
    private javax.swing.JTextArea edtReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
