package gui;

import classes.Disciplina;
import com.fasterxml.jackson.core.JsonProcessingException;
import gerenciador.GerenciadorDeDisciplinas;
import gui.dialogs.dlgCadDisciplina;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import gui.FrCadAlunoo;
import gui.FrCadProfessorr;

public class FrHome extends javax.swing.JFrame {

    List<Disciplina> listaDisciplinas;
   
    public FrHome() {
        initComponents();
        listaDisciplinas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSistemaDeGerenciamentoDeDisciplinasEscolares = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDisciplina = new javax.swing.JButton();
        btnCadAlunos = new javax.swing.JButton();
        btnCadProfessores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSistemaDeGerenciamentoDeDisciplinasEscolares.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSistemaDeGerenciamentoDeDisciplinasEscolares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSistemaDeGerenciamentoDeDisciplinasEscolares.setText("Sistema de Gerenciamento De Disciplinas Escolares");

        btnDisciplina.setText("Disciplina");
        btnDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinaActionPerformed(evt);
            }
        });

        btnCadAlunos.setText("Cad Alunos");
        btnCadAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAlunosActionPerformed(evt);
            }
        });

        btnCadProfessores.setText("Cad Professores");
        btnCadProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProfessoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadProfessores)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btnCadAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSistemaDeGerenciamentoDeDisciplinasEscolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSistemaDeGerenciamentoDeDisciplinasEscolares, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinaActionPerformed
       Disciplina novaDisciplina = new Disciplina();
       dlgCadDisciplina telaDisciplina = new dlgCadDisciplina(this, true, novaDisciplina);
       telaDisciplina.setVisible(true);
       
        System.out.println("Passei por aqui. Disciplina");
        if(novaDisciplina != null){
            listaDisciplinas.add(novaDisciplina);
        }
    }//GEN-LAST:event_btnDisciplinaActionPerformed

    private void btnCadProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProfessoresActionPerformed
        try {
            FrCadProfessorr cadProfessor = new FrCadProfessorr();
            cadProfessor.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadProfessoresActionPerformed

    private void btnCadAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAlunosActionPerformed
        try {
            FrCadAlunoo cadAluno = new FrCadAlunoo();
            cadAluno.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadAlunosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAlunos;
    private javax.swing.JButton btnCadProfessores;
    private javax.swing.JButton btnDisciplina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSistemaDeGerenciamentoDeDisciplinasEscolares;
    // End of variables declaration//GEN-END:variables
}
